### ISSUE TITLE
[v4] Add support for pg@7.x

### ISSUE THREAD

**Issue by amizz** [postgraphql/postgraphql#550] opened 2017-08-14 13:40 UTC
Node version: 8.2.1

**Dependencies:**
```json
"dependencies": {
    "express": "^4.15.4",
    "jsonwebtoken": "^7.4.2",
    "pg": "^7.1.2",
    "postgraphql": "next"
  },
"devDependencies": {
    "nodemon": "^1.11.0"
}
```

**Code:**
```javascript
const express = require('express');
const jsonwebtoken = require('jsonwebtoken');
const bodyParser = require('body-parser');
const cookieParser = require('cookie-parser');
const {
    postgraphql
} = require('postgraphql');
require('dotenv').config();

const app = express();

/**
 * Routing
 */
app.all('/', (req, res) => {
    res.status(200).json({
        message: 'Hello world!!!'
    });
});

/**
 * PostgraphQL
 */
const pgConnection = {
    host: 'localhost',
    user: 'postgres',
    password: 'postgres',
    database: 'test_db',
    port: 5432
};
const postgraphqlConfig = {
    pgDefaultRole: 'anonymous',
    graphiql: true,
};
app.use(postgraphql(pgConnection, 'public', postgraphqlConfig));

/**
 * App starts
 */
app.listen(process.env.PORT, err => {
    if (err) console.log(err);
    else console.log(`Running at http://localhost:${process.env.PORT}`);
})
```

**Error:**
```
Error: You must provide a valid PG client configuration
    at withPgClient (d:\learn\postgraphql_test\node_modules\graphile-build-pg\node8plus\withPgClient.js:47:13)
    at introspect (d:\learn\postgraphql_test\node_modules\graphile-build-pg\node8plus\plugins\PgIntrospectionPlugin.js:48:39)
    at PgIntrospectionPlugin (d:\learn\postgraphql_test\node_modules\graphile-build-pg\node8plus\plugins\PgIntrospectionPlugin.js:118:42)
    at exports.getBuilder (d:\learn\postgraphql_test\node_modules\graphile-build\node8plus\index.js:20:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Possible cause:**
The error only happens when I install/add [pg](https://www.npmjs.com/package/pg) NPM package.

**Comment by benjie** [comment] 2017-08-14 13:45
Oops, good catch - that's a regression.

**Comment by benjie** [comment] 2017-08-14 14:05
Nope, I mis-diagnosed. The issue here is that your version of `pg` and the version used internally by `graphile-build-pg` are not the same module, so our `instanceof` checks fail:

https://github.com/graphile/graphile-build/blob/ca0eda0c10f64067119e0cb4e7d9a40815a28fb8/packages/graphile-build-pg/src/withPgClient.js#L17-L24

We set it as a peer dependency here:

https://github.com/graphile/graphile-build/blob/ca0eda0c10f64067119e0cb4e7d9a40815a28fb8/packages/graphile-build-pg/package.json#L50

The actual dependency is here:

https://github.com/postgraphql/postgraphql/blob/5979eafcb2fe4c675870b265aeca8ff68d7d053e/package.json#L47

So it looks like postgraphql is installing one version of pg, but graphile-build-pg is referencing the wrong version - I expect npm/yarn will have output a bad peer dependency warning?

To resolve, change your pg version to `6.x`. I'll look into pg@7.x support.

**Comment by revolunet** [comment] 2017-09-07 10:17
having the same issue with :

 -  "pg": "^6.4.2",
 - "postgraphile": "^4.0.0-alpha2.12"

not sure how to resolve that

**Comment by revolunet** [comment] 2017-09-07 10:20
using postgraphql@next instead of postgraphile solves the issue !

should we play with postgraphile or postgraphql ?

**Comment by benjie** [comment] 2017-09-07 10:25
Please use `postgraphql@next` for now. `postgraphile` tends to lag because I don't spend the time to keep publishing - I only originally published it to reserve the package on npm so no :trollface: would steal it!

**Comment by benjie** [comment] 2017-09-07 10:26
In fact...

/me adds a deprecation message.

**Comment by revolunet** [comment] 2017-09-07 10:53
ok thanks !

**Comment by bradleyayers** [comment] 2017-10-12 23:50
What actually needs to be done to add support for pg 7?

**Comment by benjie** [comment] 2017-10-13 08:02
Don't know; it could just be updating the versions across all the package.jsons. I've not looked into it or any breaking changes yet. Have a read of the v7 changelog and let us know! 👍

**Comment by pencilcheck** [comment] 2017-11-29 03:03
I would like to know if there is a workaround to upgrade to 7, right now I suspect that some issues related to pool hang is because the older version which i'm using 6.x, and would like to upgrade but postgraphql doesn't work with 7.x

**Comment by benjie** [comment] 2017-11-29 20:03
![](https://github.trello.services/images/mini-trello-icon.png) [pg@7.x support](https://trello.com/c/2T2NN08m/14-pg7x-support)

**Comment by benjie** [comment] 2018-02-23 14:27
Fixed in https://github.com/postgraphql/postgraphql/releases/tag/v4.0.0-alpha2.31

**Closed by benjie** 2018-02-23 14:27 UTC
Labels: Fix in v4
