### ISSUE TITLE
totalCount in custom functions that return setof

### ISSUE THREAD

**Issue by barakcoh** [postgraphql/postgraphql#449] opened 2017-04-23 12:01 UTC
Hi

I have a custom python function that queries ElasticSearch and returns the result using `setof ...`. ES also returns the total number of hits. How can I include it in `totalCount`?

**Comment by mgallagher** [comment] 2017-04-27 20:52
Returning the `totalCount` is, I believe, standard behavior for a [connection procedure](https://github.com/postgraphql/postgraphql/blob/master/docs/procedures.md#connection-procedures). As far as I know, `totalCount` is just the number of rows returned by the function. So you could have something like this:

```
CREATE FUNCTION search_users(query TEXT) RETURNS SETOF user as $$
    # Query ElasticSearch and get the primary keys for the records matching the query
    matching_ids = [...]
    sql_query = plpy.prepare("SELECT * FROM person WHERE id IN ($1)", matching_ids)
    return plpy.execute(sql_query)
$$ language plpythonu stable;
```

I haven't used plpython, but the general idea here is that you can get the primary keys from ES and just return the records matching those. This should allow you to perform a GraphQL query like so:

```
query {
  searchUsers("apples") {
    totalCount
    nodes {
      id
      ...
    }
  }
}
```

Hope that helps!

**Comment by barakcoh** [comment] 2017-05-03 12:41
@mgallagher you're correct, however the problem arises when you're paginating over results because `connection procedure` has an underlying assumption that all results are returned by the function. This doesn't hold when paginating when the results returned are only a small subset of the entire result set and then `totalCount` is effectively the page size and not the total count

**Comment by mgallagher** [comment] 2017-05-12 18:33
So I just tried this out on a project of mine, here's what I did:

```
CREATE OR REPLACE FUNCTION tutor_room.my_function()
  RETURNS SETOF tutor_room.session AS $$
SELECT *
FROM tutor_room.session
ORDER BY time_in;
$$ LANGUAGE SQL STABLE;
```
Really simple function, but still a connection procedure. This query with `totalCount` and pagination info works totally fine:

```
query {
  myFunction {
    totalCount
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    nodes {
      id
    }
  }
}
```

**Comment by benjie** [comment] 2017-05-12 20:05
My guess is that @barakcoh is saying that the python function returns a subset of the total results (e.g. first 50) plus a count of the total number available (e.g. 237). PostGraphQL's totalCount will return 50 in this case since there are only 50 items in the result set from the function.

The only workaround I can think of for this is to return, instead of `setof foo`, a custom type something like `(results foo[], total_count integer)`, the values of which can then be inspected by GraphQL.

**Comment by benjie** [comment] 2017-07-09 20:30
To keep things manageable I'm going to close this issue as I think it's solved; but if not or you require further help please re-open it.

**Closed by benjie** 2017-07-09 20:30 UTC

**Comment by violeta11** [comment] 2018-02-05 18:18
Hi ,
I am trying to build a custom search function , using the above guidelines , and I think I am doing something wrong , because I am getting the following error , when trying to use postgraphql 
```error : 
   No class was found with id 60375
    at PgCatalog.assertGetClass (.....node_modules\postgraphql\build\postgres\introspection\PgCatalog.js:89:19)
    at createTypeFromPgType .....(node_modules\postgraphql\build\postgres\inventory\type\getTypeFromPgType.js:85:37)```

I am first creating the types
```
CREATE TYPE result AS (
 naam character varying(40),
 adres character varying(40),
 telefoon character varying(16),
 email character varying(85)
)

CREATE TYPE resultandtotal AS (
 data resulttest[],
 total_count integer
)
```

And thn I am using them in a function 

```
create or replace function search(start int, page int,
filterparams filter_By[] default null, orderparams order_By[] default
null) returns resultsandtotaltest as
$$ 
```
order_By and filter_By are also custom defined , the function works when I just return setof rows , It does not work when I am using the types result and resultandtotal .

I need some help )

Thank you !

**Comment by benjie** [comment] 2018-02-05 19:04
Could you try using `postgraphile` or `postgraphql@next` (they're basically the same) instead - this might have been fixed (or at least give a better/different error) in v4?

**Comment by violeta11** [comment] 2018-02-05 22:10
OK , I will .Thank you for you answer .

But if this does not work , is there a way around it ?

**Comment by benjie** [comment] 2018-02-05 22:12
Provide a minimal schema that reproduces the issue and we can dig in.

**Comment by violeta11** [comment] 2018-02-08 12:47
Thank you for your kindness .

Basically , my problem is the following :

If I am building a custom search function , how can I return , with the
results , also the total count , so that I can do pagination or infinite
scrolling ...

**Comment by benjie** [comment] 2018-02-08 13:05
[Custom queries](https://www.graphile.org/postgraphile/custom-queries/) have `totalCount` available - just use that.
