### ISSUE TITLE
Table with only one non mandatory field can't be created

### ISSUE THREAD

**Issue by freiit** [postgraphql/postgraphql#581] opened 2017-09-08 21:13 UTC
My table

    create table s.resource (
      id               uuid primary key default uuid_generate_v1mc()
    );

my query

    mutation {
      createResource(input:{ resource:{ }}) {
        resource  {
          id
        }
      }
    }

result in

    {
      "errors": [
        {
          "message": "syntax error at or near \")\"",
          "locations": [
            {
              "line": 2,
              "column": 3
            }
          ],
          "path": [
            "createResource"
          ]
        }
      ],
      "data": {
        "createResource": null
      }
    }

If I'm not using something completely wrong, this seems a bug.

**Comment by benjie** [comment] 2017-09-08 21:41
That's definitely a bug. Can you confirm if this is v3 (`postgraphql@latest`) or v4 (`postgraphql@next`) that has this issue? (Or both?)

I'm guessing the reason is it's attempting to execute something like `INSERT INTO foo () VALUES ()` whereas it should be executing `INSERT INTO foo DEFAULT VALUES` I think... It's not something I've ever had to do personally.

**Comment by freiit** [comment] 2017-09-11 09:54
I'm working directly from the git repository, master branch (`docker build ...`).
Please let me know which branch creates the newest version of @next. Then I give it another shot on that branch.

**Comment by benjie** [comment] 2017-09-11 10:16
v4's currently in issue #506 - branch is `benjie/graphql-build`

**Comment by freiit** [comment] 2017-09-11 13:20
Tried with the current version of benjie/graphql-build OR master and receive this:

```
PostGraphQL server listening on port 5000 🚀

  ‣ Connected to Postgres instance postgres://pg:5432/dev
  ‣ Introspected Postgres schema(s) cmx
  ‣ GraphQL endpoint served at http://0.0.0.0:5000/graphql
  ‣ GraphiQL endpoint served at http://0.0.0.0:5000/graphiql

* * *

TypeError: Cannot read property 'rangeType' of undefined
    at enforceGqlTypeByPgType (/usr/local/lib/node_modules/postgraphql/node_modules/graphile-build-pg/node8plus/plugins/PgTypesPlugin.js:362:45)
    at Array.forEach (<anonymous>)
    at PgTypesPlugin.builder.hook.build (/usr/local/lib/node_modules/postgraphql/node_modules/graphile-build-pg/node8plus/plugins/PgTypesPlugin.js:498:37)
    at SchemaBuilder.applyHooks (/usr/local/lib/node_modules/postgraphql/node_modules/graphile-build/node8plus/SchemaBuilder.js:149:20)
    at SchemaBuilder.createBuild (/usr/local/lib/node_modules/postgraphql/node_modules/graphile-build/node8plus/SchemaBuilder.js:177:24)
    at SchemaBuilder.buildSchema (/usr/local/lib/node_modules/postgraphql/node_modules/graphile-build/node8plus/SchemaBuilder.js:189:26)
    at SchemaBuilder.watchSchema (/usr/local/lib/node_modules/postgraphql/node_modules/graphile-build/node8plus/SchemaBuilder.js:217:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```
I do not have any issues with versions I build a few days ago.
How can I debug further?

**Comment by benjie** [comment] 2017-09-11 14:15
Sorry; I just broke that moving PostGraphQL concerns out of `graphql-build-pg` and into `postgraphile-core` instead. Upgrade to the latest `postgraphql@next` for the fix.

**Comment by freiit** [comment] 2017-09-11 14:37
Unfortunately that just changed the error message:
```
PostGraphQL server listening on port 5000 🚀

  ‣ Connected to Postgres instance postgres://pg:5432/dev
  ‣ Introspected Postgres schema(s) cmx
  ‣ GraphQL endpoint served at http://0.0.0.0:5000/graphql
  ‣ GraphiQL endpoint served at http://0.0.0.0:5000/graphiql

* * *

Error: There's already a type with the name: Locale
    at addType (/usr/local/lib/node_modules/postgraphql/node_modules/graphile-build/node8plus/makeNewBuild.js:135:15)
    at enforceGqlTypeByPgType (/usr/local/lib/node_modules/postgraphql/node_modules/graphile-build-pg/node8plus/plugins/PgTypesPlugin.js:494:7)
    at Array.forEach (<anonymous>)
    at PgTypesPlugin.builder.hook.build (/usr/local/lib/node_modules/postgraphql/node_modules/graphile-build-pg/node8plus/plugins/PgTypesPlugin.js:498:37)
    at SchemaBuilder.applyHooks (/usr/local/lib/node_modules/postgraphql/node_modules/graphile-build/node8plus/SchemaBuilder.js:149:20)
    at SchemaBuilder.createBuild (/usr/local/lib/node_modules/postgraphql/node_modules/graphile-build/node8plus/SchemaBuilder.js:177:24)
    at SchemaBuilder.buildSchema (/usr/local/lib/node_modules/postgraphql/node_modules/graphile-build/node8plus/SchemaBuilder.js:189:26)
    at SchemaBuilder.watchSchema (/usr/local/lib/node_modules/postgraphql/node_modules/graphile-build/node8plus/SchemaBuilder.js:217:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
Anything I can do about that?

**Comment by benjie** [comment] 2017-09-11 14:42
That implies you've got two things that boil down to being called "Locale" by PostGraphQL - might be e.g. `locale` and `locales`, or maybe a view and table with similar/same names?

And *YES* you can do something about that! The version I literally just released allows you to override the inflector! I've not documented it yet; but basically...

Here's the default inflectors:

https://github.com/graphile/graphile-build/blob/869dd9531a2c465392a0a8aba91157bab4d187ec/packages/graphile-build-pg/src/inflections.js#L45-L204

Here's how to build an inflector using the defaults but overriding the `enumName` field (ignore the `postGraphQLClassicIdsOverrides` variable):

https://github.com/graphile/graphile-build/blob/869dd9531a2c465392a0a8aba91157bab4d187ec/packages/postgraphile-core/src/index.js#L43-L57

And you should be able to pass your new inflector through to PostGraphQL using the undocumented `inflector` option to the library.

**Comment by benjie** [comment] 2017-09-11 14:45
So you could do, e.g.

```js
const myInflector = inflections.newInflector({
  tableName(name, _schema) {
    if (name === 'locales') {
     return "myCustomOverrideForLocales";
    } else {
      return inflections.defaultInflection.tableName(name, _schema);
    }
  },
})

app.use(postgraphql(process.env.DATABASE_URL, {inflector: myInflector}));
```

**Comment by freiit** [comment] 2017-09-11 18:10
Thanks, found the issue.

I have a type called `s.locale` and a column name in a table called `locale`. That doesn't work in v4, and maybe it's a bug?

You should be able to recreate the behavior by doing this
```
create type s.locale as enum ('a','b);
create table s.mytable (
   locale s.locale
);
```
Then the server will not start up.

**Comment by freiit** [comment] 2017-09-11 18:46
About the original issue. Its working fine in v4. So somebody can tag this issue as "fixed in v4". Thanks :-)

**Comment by benjie** [comment] 2017-09-11 19:01
I don't believe your diagnosis of the issue is correct - the column is not the issue. I suspect that you have a table or view called locale/locales and also the enum?

Failed to reproduce with:

```
$ createdb issue-581
$ psql issue-581
psql (9.6.5)
Type "help" for help.

[issue-581] # create type locale as enum('a', 'b');
CREATE TYPE
Time: 1.943 ms
[issue-581] # create table mytable ( locale locale);
CREATE TABLE
Time: 25.219 ms
[issue-581] # \q
$ postgraphql -c postgres://localhost/issue-581

PostGraphQL server listening on port 5000 🚀

  ‣ Connected to Postgres instance postgres://localhost:5432/issue-581
  ‣ Introspected Postgres schema(s) public
  ‣ GraphQL endpoint served at http://localhost:5000/graphql
  ‣ GraphiQL endpoint served at http://localhost:5000/graphiql

* * *

0 error(s) in 56.94ms :: query IntrospectionQuery { __schema { queryType { name } mutationType { name } subscriptionType { name } types { ...FullType } directives { name description locations args { ...InputValue } } } } fragment FullType on __Type { kind name description fields(includeDeprecated: true) { name description args { ...InputValue } type { ...TypeRef } isDeprecated deprecationReason } inputFields { ...InputValue } interfaces { ...TypeRef } enumValues(includeDeprecated: true) { name description isDeprecated deprecationReason } possibleTypes { ...TypeRef } } fragment InputValue on __InputValue { name description type { ...TypeRef } defaultValue } fragment TypeRef on __Type { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name } } } } } } } }
```

Query works:

```graphql
{
  allMytables{
    nodes {
      locale
    }
  }
}
```

**Comment by freiit** [comment] 2017-09-11 19:16
That is strange. Renaming my `type locale` to `xlocale` fixed the issue. I have all sql in a single place and it does not contain the words `locale`or `locales` anywhere else...

I investigate again.

**Comment by benjie** [comment] 2017-09-11 19:19
Yeah, it's clear that `type locale` is clashing with something - I just don't think it's the column (try renaming the column).

**Comment by freiit** [comment] 2017-09-12 10:03
I retried to create the "locale" issue with a fresh database and can't reproduce it. So I close that topic. Doesn't change anything on the state of this issue, as it was actually a different topic.

**Comment by benjie** [comment] 2017-09-12 10:06
Okay. Let me know if you come across the issue again. I'm going to close this as "fixed in v4" to keep things manageable.

**Closed by benjie** 2017-09-12 10:06 UTC
Labels: Fix in v4
